### ISSUE TITLE
Incorrect UI on the homepage

### ISSUE THREAD

**Issue by olivierobert** [malparty/keywords#27]
# Environment

- Platform: Web
- Device: MacBook Pro
- OS Version: Mac OS 11.3
- App Version: `main` branch
- Environment: local

# Steps to Reproduce

1. Boot the application with `dev.sh`.
2. Navigate with a browser to the URL: https://localhost:5001/.
3. Inspect the homepage

# Expected

Some UI elements meant to be hidden are actually displayed.

# Actual

This is the actual UI displayed:

![image](https://user-images.githubusercontent.com/696529/117753230-53e47980-b242-11eb-97ac-4ce7752634cb.png)

I highlighted the areas which are intended to be hidden. 

This gets weirder when uploading files 🙈 :

![image](https://user-images.githubusercontent.com/696529/117753997-a70afc00-b243-11eb-8d09-6c72f83eb1c1.png)

This issue could be caused by #26 🤔  but I am not 100% sure about it yet.

**Comment by malparty** [comment]
Yes, it's related to the style-loader error: style-loader is used to load my custom CSS styles into the header at run time. This custom style is quite small (1x hidden class to set display:none; and the layout for previewing cached Google Results). 

As it's related to #26, I'll close this issue.
