### ISSUE TITLE
Missing dependency for Bootstrap

### ISSUE THREAD

**Issue by olivierobert** [malparty/keywords#28]
# Environment

- Platform: Web
- Device: MacBook Pro
- OS Version: Mac OS 11.3
- App Version: `main` branch
- Environment: local

# Steps to Reproduce

1. Boot the application with `dev.sh`.
2. Inspect the terminal output.

# Expected

All dependencies should be defined in `/keywords/KeywordsApp/ClientApp/package.json` to ensure reproducibility of the development and production environments.

# Actual

`popper.js` is missing from the definition of the dependencies: 
![image](https://user-images.githubusercontent.com/696529/117753436-ade53f00-b242-11eb-98f7-3f4807e78a19.png)

There are also some missing attribute in `package.json` which should be referenced.

**Comment by malparty** [comment]
I can recall what happened here: I forgot the `--save` tag when uninstalling Bootstrap/Jquery/... from the project. 
Indeed these dependencies are not part of the `ClientApp` project. 
I'll fix this as well as the other UI issues first. Thanks
