### ISSUE TITLE
Handling missing userId in controllers

### ISSUE THREAD

**Issue by olivierobert** [malparty/keywords#29]
Since a user needs to be authenticated to perform any action, there are checks in each controller method:

![image](https://user-images.githubusercontent.com/696529/117754743-264cff80-b245-11eb-992b-6fe250ca7919.png)

The issues:

- Since this is repeated for every public controller method, wouldn't it better to find a way to DRY this?
- Would it make sense to return an unauthorized error (401) instead of a not found (404)?

**Comment by malparty** [comment]
Nice catch! yes, it totally make sense. 
I initially send a "NotFound()" as the "Authorized" attribute is already handling 401 (and redirection to the login page) for non-authenticated users. So as part of the object retrieval logic it seemed more like a notfound. But assuming we isolate this, indeed a 401 would makes more sense. 
For this situation, as the Authorized attribute already manage the user authentication (and confirm us the user is well loggedin), I would suggest a [403 error](https://www.freecodecamp.org/news/http-401-error-vs-http-403-error-status-code-responses-explained/).

**Comment by olivierobert** [comment]
Sure. `403` makes sense at the user is presumed authenticated past this point. The PR does resolve the issue.
