### ISSUE TITLE
JS classes implementation improvements

### ISSUE THREAD

**Issue by olivierobert** [malparty/keywords#31]
The project leverage the usage of classes in JS (so not prototype-based approach). However, the classes do seem more like a wrapper of methods instead of an actual object with attributes, public and static attributes.

1. Why not using the construct method to initialize the classes?

![image](https://user-images.githubusercontent.com/696529/117756980-5f876e80-b249-11eb-9549-485e506cbf4a.png)

This would allow changing the class invocation from:

```
$(function () {
  new UploadForm().initForm();
});
```

to:

```
$(function () {
  new UploadForm();
});
```

2. Instead of hard-coding the element selector, shouldn't be an argument in the constructor method:

![image](https://user-images.githubusercontent.com/696529/117757085-9493c100-b249-11eb-86a2-fd173b97e0a6.png)

So the end result would be:

```
$(function () {
  const $form = $('.csv-form');
  new UploadForm($form);
});
```

This would abide by the composition principle in OOP.

3. `initForm` (and other initialization methods) are fairly long and procedural. 

There are also some repetitions:

![image](https://user-images.githubusercontent.com/696529/117757492-695da180-b24a-11eb-90ec-c5839916b167.png)

This could be resolved by extracting to "private" methods and/or separate objects.

4. Using events instead of method calls to trigger JS functionality. 

`this.form.change(() => {})` adds an event handler for the `change` event. However the submit event is not leveraged and a method is called directly with `this.submitForm();`. Instead the same approach should be used `this.form.submit(() => {})` as it can be called with `this.form.submit()`.

Note that using `.on('event_type', fn())` is usually preferred for the reasons well summarize on this [StackOverflow post](https://stackoverflow.com/posts/11878976/revisions).

**Comment by malparty** [comment]
Thanks a lot for all these details, very instructive!


The stakeoverflow post related to `on` versus `eventName` handlers is interesting, though I did check before hands and [Jquery documentation](https://api.jquery.com/change/) missguided me:
> This method is a shortcut for `.on( "change", handler )` in the first two variations, and `.trigger( "change" )` in the third. 
> [...] As the `.change()` method is just a shorthand for `.on( "change", handler )`, detaching is possible using .off( "change" ).

But with the stack-o post, it makes things clearer.

While I did refactor the `on change` event, I believe I should keep the "manual submit" of the form as I'm using this form as an Ajax form. The `on('submit', ()=>{})` event does not enable me to get the response from the form submission. Most of the Ajax Form libs seems to manually parse the form and create an ajax query manually. 

As we enable more usage, I also added checks to ensure the provided element is a form:
```js
  constructor(form) {
    if (form.length > 0 && form.prop('nodeName') === 'FORM') {
      this.form = form;
      [...]
      form.on('change', this.onFormChange);
    } else {
      console.error('UploadForm needs a <form> object to work properly.');
    }
  }
```

I surely remain open to hear if I missed something here :)
