### ISSUE TITLE
Inconsistent indentation (?)

### ISSUE THREAD

**Issue by caherrerapa** [malparty/keywords#40]
I'm unsure what's the correct convention in terms of indentation.

<img width="890" alt="keywords_FileController_cs_at_main_·_malparty_keywords" src="https://user-images.githubusercontent.com/1084920/118336960-f3548580-b53c-11eb-956d-a621dba96751.png">

Checking multiple files the problem seems to keep happening, sometimes the related block is indented other times it isn't

**Comment by malparty** [comment]
Good remark, after a little search I decided to apply a block formatting to the complex queries from LinQ. 
I'm closing the issue following this #45 pull request. 

Feel free to add any comment or reopen the issue if you would have done it differently. 
Thanks!
