### ISSUE TITLE
Declaration order and cleanliness

### ISSUE THREAD

**Issue by caherrerapa** [malparty/keywords#42]
We have a not so clean way to do declarations:
- Extra line after headers.
- We don't group the declarations by type. e.g. We have Stream, long, string, IHeaderDictionary, string, string.

![keywords_UploadFormViewModel_cs_at_main_·_malparty_keywords](https://user-images.githubusercontent.com/1084920/118345933-26f5d680-b562-11eb-97e0-350abab8db4b.jpg)

**Comment by malparty** [comment]
Thanks a lot for this feedback, I hope PR #49 fixed the issue.
